name = "bk"
license = "MIT"
licenselink = "https://github.com/kapusuzoglu/blogTheme/blob/main/LICENSE"
description = "BK - Privacy focused theme for Hugo using TailwindCSS"

homepage = "https://github.com/kapusuzoglu/blogTheme"

demosite = "https://kapusuzoglu.github.io"

tags = ["Blog", "AI", "Machine Learning", "Deep Learning", "Personal development", "Large Language Models"]
features = ["Isso comments", "umami analytics", "SVG icons", "automatic dark mode", "deeplinks"]

[author]
  name = "Berkcan Kapusuzoglu"
  homepage = "https://github.com/kapusuzoglu/"

[original]
  author = "Dirk Olbrich"
  homepage = "https://github.com/dirkolbrich"
  repo = "https://github.com/dirkolbrich/hugo-theme-tailwindcss-starter"

[module]
  [module.hugoVersion]
    extended = true
    min_version = "0.69"